apiVersion: v1
kind: PersistentVolume
metadata:
  name: notificaciones-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/notificaciones-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notificaciones-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi