apiVersion: apps/v1
kind: Deployment  # Tipo: Deployment
metadata:
  name: tareas-deployment
spec:
  replicas: 1  # Número de pods (empieza con 1, puedes escalar después)
  selector:
    matchLabels:
      app: tareas
  template:
    metadata:
      labels:
        app: tareas
    spec:
      containers:
      - name: tareas
        image: tareas:latest  # Tu imagen Docker
        ports:
        - containerPort: 8000  # Puerto del contenedor
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service  # Tipo: Service
metadata:
  name: tareas-service
spec:
  selector:
    app: tareas  # Apunta al Deployment
  ports:
  - protocol: TCP
    port: 80  # Puerto del service
    targetPort: 8000  # Puerto del pod
  type: NodePort  # Accesible desde fuera (para pruebas locales)