apiVersion: v1
kind: PersistentVolume
metadata:
  name: usuarios-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi  
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/usuarios-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: usuarios-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi