# Generated by Django 5.2.5 on 2025-08-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea_uuid', models.UUIDField()),
                ('mensaje', models.TextField()),
                ('enviada_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
