# Generated by Django 5.2.5 on 2025-08-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='usuario_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
